import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { assets, projects, type Project } from './data/projects'
import './styles.css'

function useScrollLock(locked: boolean) { useEffect(() => { if (!locked) return; const original = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = original } }, [locked]) }

function Header() {
  const [menuOpen, setMenuOpen] = useState(false); const close = () => setMenuOpen(false)
  return <header className="header"><a className="brand" href="#top" aria-label="Диана Вольф, в начало">DV<span>°</span></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-controls="site-menu"><span>{menuOpen ? 'Закрыть' : 'Меню'}</span><i aria-hidden="true" /></button><nav id="site-menu" className={menuOpen ? 'nav nav--open' : 'nav'} aria-label="Основная навигация"><a onClick={close} href="#works">Работы</a><a onClick={close} href="#about">Обо мне</a><a onClick={close} href="#skills">Навыки</a><a onClick={close} href="#contact">Контакты</a></nav></header>
}
function Hero() {
  return <section id="top" className="hero"><p className="eyebrow hero__eyebrow">Graphic Designer <span>Tomsk / 2026</span></p><div className="hero__title" aria-label="Диана Вольф"><span>ДИАНА</span><span>ВОЛЬФ</span></div><div className="hero__paper">визуальный дизайн<br />и печатная магия</div><span className="hero__spark" aria-hidden="true">✦</span><p className="hero__description">Визуальный дизайн, айдентика<br />и многостраничная продукция.</p><a className="scroll-hint" href="#works">scroll to explore <span>↓</span></a></section>
}
function ProjectIndex({ openProject }: { openProject: (project: Project) => void }) {
  const [active, setActive] = useState<Project | null>(null); const preview = useRef<HTMLDivElement>(null)
  const movePreview = (event: PointerEvent<HTMLDivElement>) => { if (preview.current) preview.current.style.transform = `translate3d(${event.clientX + 22}px, ${event.clientY - 150}px, 0)` }
  return <section className="works" id="works" aria-labelledby="works-title"><div className="section-top"><p className="eyebrow">selected projects</p><h2 id="works-title">Избранные<br /><em>работы</em></h2><p>2025 — 2026</p></div><div className="project-index" onPointerMove={movePreview}>{projects.map((project) => <button key={project.id} className={`project-row project-row--${project.theme}`} onMouseEnter={() => setActive(project)} onFocus={() => setActive(project)} onMouseLeave={() => setActive(null)} onBlur={() => setActive(null)} onClick={() => openProject(project)}><span className="project-row__number">{project.number}</span><span className="project-row__title">{project.title}</span><span className="project-row__meta">{project.tags[0]} <b>↗</b></span></button>)}</div>{active && <div ref={preview} className="cursor-preview" aria-hidden="true"><img src={active.cover} alt="" decoding="async" /><span>Открыть кейс</span></div>}<p className="works__note">Наведите на название<br />или выберите работу</p></section>
}
function ProjectCases({ openProject }: { openProject: (project: Project) => void }) { return <section className="case-gallery" aria-label="Превью проектов">{projects.map((project, index) => <article key={project.id} className={`case-card case-card--${project.theme} ${index % 2 ? 'case-card--offset' : ''}`}><button onClick={() => openProject(project)} aria-label={`Открыть проект ${project.title}`}><img src={project.cover} alt={`Проект «${project.title}»`} loading="lazy" decoding="async" fetchPriority="low" /><span className="case-card__label"><i>{project.number}</i><b>{project.title}</b><em>Смотреть ↗</em></span></button></article>)}</section> }
function About() { return <><section className="about" id="about" aria-labelledby="about-title"><p className="about__ghost" aria-hidden="true">ОБО<br />МНЕ</p><img src={assets.about} alt="Диана Вольф" loading="lazy" decoding="async" fetchPriority="low" /><div className="about__copy"><p className="eyebrow">01 / about me</p><h2 id="about-title">Дизайн —<br />это <em>внимание</em><br />к деталям.</h2><p>Начинающий графический дизайнер из Томска. Создаю визуальные решения для печатной и рекламной продукции, айдентики и многостраничных изданий.</p></div></section><div className="ticker" aria-label="Направления работы"><div>ЛОГОТИПЫ <span>•</span> EDITORIAL <span>•</span> АФИШИ <span>•</span> BRANDING <span>•</span> PRINT <span>•</span> ЖУРНАЛЫ <span>•</span></div></div></> }
function Skills() { return <section className="skills" id="skills" aria-labelledby="skills-title"><div><p className="eyebrow">02 / toolkit</p><h2 id="skills-title">Работаю<br />в <em>системе</em></h2></div><ul className="skills__list"><li><i>PS</i>Adobe Photoshop</li><li><i>AI</i>Adobe Illustrator</li><li><i>ID</i>Adobe InDesign</li></ul><div className="qualities"><span>внимание к деталям</span><span>самоорганизация</span><span>ответственность</span><span>дисциплина</span><span>работа с ТЗ</span></div></section> }
function Contact() { return <section className="contact" id="contact" aria-labelledby="contact-title"><p className="eyebrow">Есть проект?</p><h2 id="contact-title">Давайте<br /><em>обсудим.</em></h2><p className="contact__sub">Вы можете написать мне в Telegram<br />или отправить письмо.</p><div className="contact__actions"><a className="magnetic" href="https://t.me/Vol_hsu" target="_blank" rel="noopener noreferrer">Написать мне <span>↗</span></a><a href="mailto:d1ana.volf@yandex.ru">d1ana.volf@yandex.ru</a></div><footer><span>DIANA VOLF<br />GRAPHIC DESIGNER</span><span>© 2026</span><a href="#top">Back to top ↑</a></footer></section> }
function CaseDialog({ project, close, next }: { project: Project, close: () => void, next: () => void }) { const closeButton = useRef<HTMLButtonElement>(null); useScrollLock(true); useEffect(() => { closeButton.current?.focus() }, []); useEffect(() => { const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') close() }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) }, [close]); return <div className={`dialog dialog--${project.theme}`} role="dialog" aria-modal="true" aria-labelledby="case-title"><div className="dialog__bar"><span>DIANA VOLF / SELECTED WORK</span><button ref={closeButton} onClick={close} aria-label="Закрыть проект">Закрыть <b>×</b></button></div><main className="case"><header><p className="eyebrow">{project.number} / {project.year}</p><h2 id="case-title">{project.title}</h2><p className="case__subtitle">{project.subtitle}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></header><div className="case__lead"><p>{project.description}</p><span>Scroll to explore ↓</span></div><div className="case__images">{project.images.map((image, i) => <figure key={image} className={i === 0 ? 'case__image case__image--hero' : 'case__image'}><img src={image} alt={`${project.title}: ${i === 0 ? 'обложка проекта' : 'детали работы'}`} /></figure>)}</div><button className="next-project" onClick={next}>Следующий проект <span>→</span></button></main></div> }
function App() { const [selected, setSelected] = useState<Project | null>(null); const nextProject = () => { if (selected) setSelected(projects[(projects.indexOf(selected) + 1) % projects.length]) }; return <><Header /><main><Hero /><ProjectIndex openProject={setSelected} /><ProjectCases openProject={setSelected} /><About /><Skills /><Contact /></main>{selected && <CaseDialog project={selected} close={() => setSelected(null)} next={nextProject} />}</> }
export default App
